spring.application.name=ecommerce-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce_db
spring.datasource.username=postgres
spring.datasource.password=983301

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=8c4f8e9a2d1b6f7c5a9e3d8b1f6c7a2e4d9b8f1c6a7e5d3b9f2a8c6e1d7f4b5
jwt.expiration=86400000